-- 1.What are the details of all cars purchased in the year 2022?
SELECT c.car_id,c.make,c.type,c.style,s.purchase_date
FROM cars AS c
JOIN sales AS s
ON c.car_id=s.car_id
WHERE YEAR(s.purchase_date) =2022
/*
1	Honda	Civic	Sedan	2022-02-03
1	Honda	Civic	Sedan	2022-07-09
2	Toyota	Corolla	Hatchback	2022-01-01
3	Ford	Explorer	SUV	2022-05-05
5	BMW	X5	SUV	2022-04-02
5	BMW	X5	SUV	2022-06-07
7	Mercedes	C-Class	Coupe	2022-03-01
8	Nissan	Altima	Sedan	2022-02-10*/

-- 2. What is the total number of cars sold by each salesperson?

  SELECT COUNT(s.sale_id) AS Num_car_sold,sp.name
  FROM sales AS s
  JOIN salespersons  AS sp
  ON s.salesman_id=sp.salesman_id
  GROUP BY sp.name
  ORDER BY Num_car_sold
  
  -- 3.What is the total revenue generated by each salesperson?
  SELECT s.salesman_id,sp.name,SUM(c.cost_$) AS Revenue
  FROM cars AS c 
  JOIN sales AS s 
  ON c.car_id=s.car_id
  JOIN salespersons AS sp ON s.salesman_id=sp.salesman_id
  GROUP BY s.salesman_id,sp.name
  ORDER BY Revenue DESC
  -- Tom Lee had a revenue of $253,000
  -- John Smith had a revenue of $181,000
  -- Emily Wong had a revenue of $177,000
  -- Lucy Chen had a revenue of $171,000
  
  
  -- 4.What are the details of the cars sold by each salesperson?
  SELECT c.car_id,s.salesman_id,sp.name,c.make,c.type,c.style
  FROM cars AS c 
  JOIN sales AS s 
  ON c.car_id=s.car_id
  JOIN salespersons AS sp ON s.salesman_id=sp.salesman_id
  GROUP BY  s.salesman_id,sp.name,c.car_id,c.make,c.type,c.style
  
  -- 5.What is the total revenue generated by each car type?
SELECT c.type,COUNT(sale_id) AS Num_cars_sold,SUM(cost_$)AS Revenue
FROM cars AS c
JOIN sales AS s
ON c.car_id=s.car_id
GROUP BY c.type


-- 6.What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
  SELECT c.car_id,c.type,c.style,c.make
  FROM cars AS c 
  JOIN sales AS s 
  ON c.car_id=s.car_id
  JOIN salespersons AS sp ON s.salesman_id=sp.salesman_id
  WHERE sp.name='Emily Wong' AND YEAR(purchase_date)=2021
  -- The details of the cars sold by Emily Wong in 2021 are TYPE:COROLLA ,STYLE:HATCHBACK MAKE:TOYOTA
-- 															TYPE:CAMARO,STYLE:COUPE,MAKE:CHEVROLET
 
 -- 7.What is the total revenue generated by the sales of hatchback cars?
SELECT c.style,SUM(c.cost_$) AS Revenue
FROM cars AS c 
JOIN sales AS s 
ON c.car_id=s.car_id
WHERE  c.style='Hatchback'
GROUP BY c.style
ORDER BY Revenue DESC
-- The total revenue generated by Hatchbacks $100,000


-- 8. What is the total revenue generated by the sales of SUV cars in the year 2022?
SELECT c.style,SUM(c.cost_$) AS Revenue
FROM cars AS c 
JOIN sales AS s 
ON c.car_id=s.car_id
WHERE  c.style='SUV'
GROUP BY c.style
ORDER BY Revenue DESC
-- The Total Revenue Generated by SUVs $300,000

-- 9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?
SELECT COUNT(s.sale_id) AS Num_car_sold,sp.name,sp.city
FROM sales AS s
JOIN salespersons  AS sp
  ON s.salesman_id=sp.salesman_id
  WHERE YEAR(purchase_date)=2023
  GROUP BY sp.name,sp.city
  ORDER BY Num_car_sold desc
  LIMIT 1
  -- Tom Lee Sold 2cars in 2023 and his city is Seattle
  
  -- 10.What is the name and age of the salesperson who generated the highest revenue in the year 2022
  SELECT s.salesman_id,sp.name,sp.age,SUM(c.cost_$) AS Revenue
  FROM cars AS c 
  JOIN sales AS s 
  ON c.car_id=s.car_id
  JOIN salespersons AS sp ON s.salesman_id=sp.salesman_id
  WHERE YEAR(purchase_date)=2022
  GROUP BY s.salesman_id,sp.name,sp.age
  ORDER BY Revenue DESC
  LIMIT 1
  -- Emily Wong had the highest revenue in 2002 She was 35 years old